In [49]:
from IPython.core.interactiveshell import InteractiveShell

InteractiveShell.ast_node_interactivity = "all"

# Numpy usage

## NUMPY STRUCTURES : ARRAYS
There are many to create numpy structures:
1. python lists
2. numpy methods
3. random

In [4]:
import numpy as np

In [5]:
#1
my_list = [1,2,3,4,5]
my_matrix = [[1,2,3], [4,5,6]]
print(np.array(my_list))
print(np.array(my_matrix))

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [29]:
#2
print('arange: generates a range from 0 to end(not include)')
print(np.arange(10))
print(np.arange(0, 11, 2))
print('zeros: generates a matrix/array of 0')
print(np.zeros(3))
print(np.zeros((5,5)))
print('ones:  generates a matrix/array of 1')
print(np.ones(3))
print('linear space:')
print(np.linspace(0,10,3))
print('eye:')
print(np.eye(3))

arange: generates a range from 0 to end(not include)
[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10]
zeros: generates a matrix/array of 0
[0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
ones:  generates a matrix/array of 1
[1. 1. 1.]
linear space:
[ 0.  5. 10.]
eye:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [36]:
#3
uniform_dist = np.random.rand(2) # samples from a uniform distribution over [0, 1)
uniform_dist_matrix = np.random.rand(5,5) # idem with more dimensions

std_dist = np.random.randn(2) # sample (or samples) from the "standard normal" distribution
std_dist_matrix = np.random.randn(5,5) # sample (or samples) from the "standard normal" distribution

rand_int = np.random.randint(1,100) # integers from low (inclusive) to high (exclusive)
rand_int_matrix = np.random.randint(1,100,10) #integers from low (inclusive) to high (exclusive)


## NUMPY OPERATIONS OVER ARRAYS


In [50]:
arr = np.arange(10)
ranarr = np.random.randint(0,50,10)
print(arr)
print(ranarr)
#reshape
arr.reshape(2,5)

#max, min, argmax, argmin
ranarr.max()
ranarr.min()
ranarr.argmax()
ranarr.argmin()

[0 1 2 3 4 5 6 7 8 9]
[ 7 15 16 34 29 27 11  6 34 22]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

34

6

3

7

## ARRAY ATRIBUTES

In [58]:
ranarr.reshape(2,5,1).shape

(2, 5, 1)

In [59]:
arr.dtype

dtype('int32')

## Indexing arrays

Is possible to acces the N-element or a slice with the [] and the [:]
Also, a value can be assigned to a slice of a matrix/array.

## Copy
For default, the assign of a variable is by reference, to perform a copy 
is necesarry to specifie the ``.copy()`` method.

In [65]:
ranarr[3]
ranarr[3:7]
ranarr[0:2] = -3
ranarr

34

array([34, 29, 27, 11])

array([-3, -3, 16, 34, 29, 27, 11,  6, 34, 22])

## Indexing matrixs

The matrix access is with this prototype : [row] or [row, column] or [row][column]. Also is possible to use python slices.


In [66]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [69]:
arr_2d[1][0]
arr_2d[1]
arr_2d[:2, 1:]

20

array([20, 25, 30])

array([[10, 15],
       [25, 30]])

## Matrix elements operations
Is possible to select several rows, by index.
Also, boolean conditions can be applied.

In [92]:
arr_2d
arr_2d[[1,2,0]]
bool_arr = arr_2d >= 30
arr_2d[bool_arr]
arr_2d[arr_2d > 25]

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

array([[20, 25, 30],
       [35, 40, 45],
       [ 5, 10, 15]])

array([30, 35, 40, 45])

array([30, 35, 40, 45])

## Arithmetic operations

In [102]:
a1 = np.arange(0,10)
a1
a1 + a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [98]:
a1.dot(a1)

285

In [99]:
a1 - a1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [101]:
np.sqrt(a1)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [103]:
np.exp(a1)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])