### Importar la libreria

In [2]:
import numpy as np

## Creando Arrays de Numpy

### Desde listas de Python

In [3]:
my_list = [1,2,3]
np.array(my_list)

array([1, 2, 3])

In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Usando métodos incluidos en Numpy

#### arange

In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

#### zeros & ones

In [7]:
np.zeros(3)

array([0., 0., 0.])

In [8]:
np.zeros((5,5,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [9]:
np.ones(3)

array([1., 1., 1.])

In [10]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### linspace

In [11]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [12]:
np.linspace(0,10,51)

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
        4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
        6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
        8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. ])

#### eye

In [13]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### random

In [14]:
np.random.rand(2) # samples from a uniform distribution over [0, 1)

array([0.4412359 , 0.50504673])

In [15]:
np.random.rand(5,5) # samples from a uniform distribution over [0, 1)

array([[1.65316437e-03, 5.44546226e-01, 6.32614220e-01, 9.18155423e-01,
        3.51906471e-01],
       [6.44120544e-02, 3.15359926e-01, 3.21851007e-01, 9.86561700e-01,
        5.27129572e-01],
       [5.80045922e-01, 8.69312389e-01, 2.01568698e-01, 6.62157772e-01,
        3.92406218e-01],
       [9.61081022e-01, 9.77097896e-01, 1.93586829e-01, 7.08653682e-01,
        6.27470682e-04],
       [6.46156436e-01, 4.05221981e-01, 3.41749911e-02, 6.79529477e-01,
        9.05287436e-01]])

In [16]:
np.random.randn(2) # sample (or samples) from the "standard normal" distribution

array([-0.58667362,  0.44353737])

In [17]:
np.random.randn(5,5) # sample (or samples) from the "standard normal" distribution

array([[-0.499588  ,  0.87289179, -0.55231137, -0.62244208, -0.91067876],
       [ 0.31472311,  0.14221379, -1.00552898,  0.06896401, -0.43681301],
       [-0.62738016,  1.08282938, -1.25397581, -0.29662628, -1.05875613],
       [ 0.7138452 , -1.67388834, -1.1550254 ,  1.6789    ,  1.55375885],
       [-0.48643029,  1.68986601,  1.33305856,  2.11813303,  0.66438248]])

In [18]:
np.random.randint(1,100) # integers from low (inclusive) to high (exclusive)

32

In [19]:
np.random.randint(1,100,10) #integers from low (inclusive) to high (exclusive)

array([ 8, 10, 45, 57, 33, 26, 96, 98, 17, 80])

## Operaciones sobre arrays Numpy

In [20]:
arr = np.arange(100)
ranarr = np.random.randint(0,50,10)

### reshape

In [24]:
arr.reshape(20,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

### max, min, argmax, argmin

In [25]:
ranarr

array([30,  8, 20, 39, 21, 17, 32, 46, 36, 14])

In [26]:
ranarr.max()

46

In [27]:
ranarr.argmax()

7

In [28]:
ranarr.min()

8

In [29]:
ranarr.argmin()

1

## Atributos

### Shape

In [30]:
arr.shape

(100,)

In [32]:
arr.reshape(1,100)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
        64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
        80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [33]:
arr.reshape(1,100).shape

(1, 100)

In [34]:
arr.reshape(100,1,1)

array([[[ 0]],

       [[ 1]],

       [[ 2]],

       [[ 3]],

       [[ 4]],

       [[ 5]],

       [[ 6]],

       [[ 7]],

       [[ 8]],

       [[ 9]],

       [[10]],

       [[11]],

       [[12]],

       [[13]],

       [[14]],

       [[15]],

       [[16]],

       [[17]],

       [[18]],

       [[19]],

       [[20]],

       [[21]],

       [[22]],

       [[23]],

       [[24]],

       [[25]],

       [[26]],

       [[27]],

       [[28]],

       [[29]],

       [[30]],

       [[31]],

       [[32]],

       [[33]],

       [[34]],

       [[35]],

       [[36]],

       [[37]],

       [[38]],

       [[39]],

       [[40]],

       [[41]],

       [[42]],

       [[43]],

       [[44]],

       [[45]],

       [[46]],

       [[47]],

       [[48]],

       [[49]],

       [[50]],

       [[51]],

       [[52]],

       [[53]],

       [[54]],

       [[55]],

       [[56]],

       [[57]],

       [[58]],

       [[59]],

       [[60]],

       [[61]],

       [

In [35]:
arr.reshape(100,1,1).shape

(100, 1, 1)

### dtype

In [36]:
arr.dtype

dtype('int64')

## Selección y indexado de Arrays

In [37]:
arr[8]

8

In [38]:
arr[0:5]

array([0, 1, 2, 3, 4])

### Broadcasting

In [39]:
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99])

In [41]:
slice_of_arr = arr[0:6]
slice_of_arr[:]=99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [42]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

### copia

In [43]:
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

## Selección y indexado de Matrices

In [44]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [45]:
arr_2d[1] # Selección de fila

array([20, 25, 30])

In [47]:
arr_2d[1][0] # Selección de elemento
arr_2d[1,0]

20

In [49]:
arr_2d[:2, 1:] # Forma (2,2) desde la esquina superior derecha

array([[10, 15],
       [25, 30]])

In [50]:
arr_2d[:,2]


array([15, 30, 45])

## Selección avanzada

In [51]:
arr = np.arange(1,11)
arr2d = np.zeros((10,10))
arr_length = arr2d.shape[1]
for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [52]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [53]:
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

In [54]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [56]:
bool_arr = arr > 4

In [57]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [58]:
arr[arr > 2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

## Operaciones aritméticas

In [61]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [63]:
arr.dot(arr)

285

In [64]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [65]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [66]:
# OJO Cuidado, lanza warning de división por 0, pero no lanza un error!
# Remplaza con un nan
arr/arr

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [67]:
# OJO Cuidado, como en el caso anterior, avisa, pero no lanza un error!
# Remplaza por inf
1/arr

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [68]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

## Funciones universales de Arrays

In [69]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [70]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [71]:
np.argmax(arr)

9

In [72]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [74]:
np.log(arr) ## Cuidado!

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

# Buen Trabajo!